version: '3'

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tips
      MYSQL_USER: hello
      MYSQL_PASSWORD: world
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: hello
      PMA_PASSWORD: world
    restart: always
    ports:
      - 8080:80
    links: 
      - mysql:db
    depends_on: 
      - mysql

volumes:
  mysql-data:
    driver: local