version: '3'
services:
  minio:
    image: minio/minio
    command: ["server","--compat", "/data"]
    environment:
      ## https://docs.min.io/docs/minio-docker-quickstart-guide.html
      MINIO_ACCESS_KEY: ACCESS_KEY
      MINIO_SECRET_KEY: SECRET_KEY
    ports:
      - "9999:9000"
    volumes:
      - ./data:/export

  # cli tools
  minio-support:
    image: minio/mc
    entrypoint: [""]
    command:
      - /bin/sh
      - -c
      - |
        mc config host add minio http://minio:$${MINIO_PORT} $${MINIO_ACCESS_KEY} $${MINIO_SECRET_KEY} --api S3v4
        mc admin trace minio
    environment:
      MINIO_PORT: 9999
      MINIO_ACCESS_KEY: ACCESS_KEY
      MINIO_SECRET_KEY: SECRET_KEY
    depends_on:
      - minio