version: '3'
services:
  minio:
    image: minio/minio:lastest
    command: ["server","--compat", "/data"]
    environment:
      ## https://docs.min.io/docs/minio-docker-quickstart-guide.html
      MINIO_ACCESS_KEY: ACCESS_KEY
      MINIO_SECRET_KEY: SECRET_KEY
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
  minio-support:
    image: minio/mc:lastest
    entrypoint: [""]
    command:
      - /bin/sh
      - -c
      - |
        mc config host add minio http://minio:$${MINIO_PORT} $${MINIO_ACCESS_KEY} $${MINIO_SECRET_KEY} --api S3v4
        mc admin trace minio
    environment:
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: ACCESS_KEY
      MINIO_SECRET_KEY: SECRET_KEY
    depends_on:
      - minio