version: "3"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
    ports:
      - "5432:5432"
    volumes:
        - postgres-data:./data

  postgres-gui:
    image: donnex/pgweb
    command: -s --bind=0.0.0.0 --listen=8080 --url postgresql://test:@postgres/test?sslmode=disable
    links:
      - postgres:postgres
    ports:
      - "8080:8080"
volumes:
  postgres-data:
    driver: local