version: '3'
services:

  redis:
    container_name: redis-container
    image: redis:5
    command: redis-server --appendonly yes --requirepass foobared
    volumes:
       - redis-data:/data
    ports:
      - "6379:6379"

  redisCommander:
    container_name: redis-commander-container
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOSTS: Index0:redis-container:6379:0:foobared,Index1:redis-container:6379:1:foobared
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  redis-data:
    driver: local